function(option_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    if(${value})
        message(STATUS "${status_text}  : ON")
    else()
        message(STATUS "${status_text}  : OFF")
    endif()
endfunction()

function(string_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    string(TOLOWER ${value} status_value)
    message(STATUS "${status_text}  : ${status_value}")
endfunction()

function(lib_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    message(STATUS "${status_text}  : ${value}")
endfunction()

option (ENABLE_CLANG_TIDY "Enable clang-tidy analyizer" OFF)
option (ENABLE_IWYU "Enable include-what-you-include analyizer" OFF)

if (ENABLE_CLANG_TIDY)
  set(CMAKE_CXX_CLANG_TIDY clang-tidy)
endif (ENABLE_CLANG_TIDY)

if (ENABLE_IWYU)
  set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE include-what-you-use)
endif (ENABLE_IWYU)